apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3k.fullname" . }}
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.image.replicaCount }}
  selector:
     matchLabels:
      {{- include "k3k.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k3k.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: webhook-serving
          secret:
            secretName: webhook-secret
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
          - containerPort: 8080
            name: https
            protocol: TCP
          - containerPort: 9443
            name: https-webhook
            protocol: TCP
          volumeMounts:
            - name: webhook-serving
              readOnly: true
              mountPath: "/tmp/k8s-webhook-server/serving-certs"
      serviceAccountName: {{ include "k3k.serviceAccountName" . }}
