apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "k3k.io.clusterset"
webhooks:
- name: "clusters.k3k.io"
  rules:
  - apiGroups:   ["k3k.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["clusters"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: {{ include "k3k.fullname" . }}-webhook
      namespace: {{ .Values.namespace }}
      path: /validate-k3k-io-v1alpha1-cluster
    caBundle: >
      ReplaceMe
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "k3k.io.clusterset-default"
webhooks:
- name: "clusters.k3k.io"
  rules:
  - apiGroups:   ["k3k.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE"]
    resources:   ["clusters"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: {{ include "k3k.fullname" . }}-webhook
      namespace: {{ .Values.namespace }}
      path: /mutate-k3k-io-v1alpha1-cluster
    caBundle: >
      ReplaceMe
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10

