apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cidrallocationpools.k3k.io
spec:
  group: k3k.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                defaultClusterCIDR: 
                  type: string
            status:
              type: object
              properties:
                pool:
                  type: array
                  items:
                    type: object
                    properties:
                      clusterName: 
                        type: string
                      issued: 
                        type: integer
                      ipNet:
                        type: string
  scope: Cluster
  names:
    plural: cidrallocationpools
    singular: cidrallocationpool
    kind: CIDRAllocationPool
