on:
  push:
    branches:
      - master
  pull_request:

name: Build
permissions:
    contents: read
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Dapper
      run: |
        curl -sL https://releases.rancher.com/dapper/latest/dapper-$$(uname -s)-$$(uname -m) > .dapper.tmp && \
        chmod +x .dapper.tmp && \
        ./.dapper.tmp -v && \
        mv .dapper.tmp .dapper

    - name: Build
      run: |
        ./.dapper ci
      env:
        CROSS: "true"
        